# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [13]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [33]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/LAVANYA/anaconda3/Library/include
    lib directory: C:/Users/LAVANYA/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host

#### 3. Create a null vector of size 10

In [29]:
c=np.zeros((10))
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [94]:
arr=np.zeros((3,3))
print(arr.size*arr.itemsize)

72


#### 5.  How to get the documentation of the numpy add function from the command line? 

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [39]:
arr= np.zeros((10))
arr[4]=1;
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [43]:
arr=np.arange(10,50,1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [47]:
arr=arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
arr1=np.random.randint(0,9,(3,3))
print(arr1)

[[2 2 3]
 [3 4 6]
 [8 5 7]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [53]:
arr=np.array([1,2,0,0,4,0])
for i in range(len(arr)):
    if (arr[i]!=0):
        print(i,end=" ")

0 1 4 

#### 11. Create a 3x3 identity matrix

In [55]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [59]:
c=np.random.random((3,3,3))
print(c)

[[[0.44456106 0.66326358 0.94994203]
  [0.9979078  0.10838316 0.75736635]
  [0.03324078 0.96072548 0.41715885]]

 [[0.12683476 0.15506899 0.24328411]
  [0.34709752 0.23031496 0.51631424]
  [0.18483977 0.86555186 0.21732014]]

 [[0.80066047 0.12337334 0.38394582]
  [0.66968981 0.50755341 0.25721255]
  [0.47106907 0.17657262 0.55162196]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [61]:
c=np.random.random((10,10))
print("Minimum: ",c.min())
print("Maximum: ",c.max())

Minimum:  0.021196826605450414
Maximum:  0.9905494802628471


#### 14. Create a random vector of size 30 and find the mean value

In [67]:
c=np.random.random((30))
print("Mean: ",c.mean())

Mean:  0.611457585234928


#### 15. Create a 2d array with 1 on the border and 0 inside

In [87]:
a=np.zeros((3,3))
a[0:1,0:3]=1
a[0:3,0:1]=1
a[2:3,0:3]=1
a[0:3,2:3]=1
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [23]:
arr=np.diag([1,2,3,4],k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. What is the result of the following expression

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [112]:
arr=np.ones((8,8))
arr[::2,::2]=0
arr[1::2,1::2]=0
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
